services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql+asyncpg://ims_user:ims_pass_123@postgres:5432/ims
      - MONGO_URL=mongodb://mongo:27017/ims
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - postgres
      - mongo

  worker:
    build: ./backend
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql+asyncpg://ims_user:ims_pass_123@postgres:5432/ims
      - MONGO_URL=mongodb://mongo:27017/ims
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - postgres
      - mongo
    command: celery -A app.ims.worker worker --loglevel=info --concurrency=4

  postgres:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_DB: ims
      POSTGRES_USER: ims_user
      POSTGRES_PASSWORD: ims_pass_123
    volumes:
      - ./backend/migrations:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  postgres_data:
  mongo_data: